project:
  type: website
  output-dir: _site

website:
  title: "CD2030 Datasuite Vaxx Guide"

  site-url: https://aphrcwaro.github.io/vaxx_guide/
  repo-url: https://github.com/aphrcwaro/vaxx_guide
  repo-actions: [edit, issue]

  page-footer:
    right: |
      Built with <a href="https://quarto.org">Quarto</a>

  sidebar:
    contents:
      - index.qmd

      - section: About this Guide
        contents:
          - pages/general-intro.qmd
          - pages/getting-started.qmd
          - pages/app-features.qmd
          - pages/loading-data.qmd

      - section: Data Quality Assessment
        contents:
          - pages/numerator-assessment.qmd
          - pages/numerator-adjustments.qmd
          - pages/denominator-assessment.qmd

      - section: National Analyses
        contents:
          - pages/national-coverage.qmd
          - pages/national-inequality.qmd
          - pages/national-global-coverage.qmd
          - pages/national-subnational-mapping.qmd
          - pages/national-equity-assessment.qmd

      - section: Sub-national Analyses
        contents:
          - pages/subnational-coverage.qmd
          - pages/subnational-inequality.qmd
          - pages/subnational-global-coverage.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    code-link: true

execute:
  echo: false
  warning: false
  message: false

lang: en
bibliography: references.bib

# Multilingual configuration
babelquarto:
  mainlanguage: en
  languages:
    - fr
    - pt

  languagecodes:
    - name: en
      text: "English"
    - name: fr
      text: "Français"
    - name: pt
      text: "Português"